mod 'puppet-nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
mod 'puppetlabs-docker'
mod 'puppetlabs/apt'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mode'puppetlabs/reboot'

