mod 'puppet-nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'pltraining/dockeragent'
# mod 'garethr-docker', '5.3.0'
mod 'puppetlabs-docker', '3.3.0'
mod 'puppetlabs/apt'
mod 'puppetlabs/translate'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'

